In [1]:
import os
import numpy as np
import pandas as pd

zs = True
node_file = './skoly_graph/nodes.csv'
out_dir = './skoly_graph/nodes_with_class_groups/'
seed = 42
n_files = 5

In [2]:
if not os.path.exists(out_dir):
    os.mkdir(out_dir)

node_df = pd.read_csv(node_file, index_col=0)
node_df

,id,sex,age,class,Atletika,Basketbal,Bricks 4 kidz,Dílnička pro holky,Florbal,Fotbal,...,Zájmové: Příprava k přijímacím zkouškám na SŠ - matematika,Zájmové: Počítačová grafika,asistent_trida1A,asistent_trida5A,pedagog3C,pedagog4C,pedagog5B,pedagog5C,x,y
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.034904,6.012715
1,2,NaN,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.946986,5.888305
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.818483,5.922031
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.007333,5.951234
4,5,NaN,50-59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.112896,5.954979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
674,1626,NaN,7,2C,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.858112,2.941083
675,1627,NaN,7,2B,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.918972,2.148378
676,1628,NaN,7,2A,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.955486,1.015996
677,1629,NaN,7,2C,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.929262,3.114258
678,1630,NaN,7,2C,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.097124,3.045137

In [3]:
students = (node_df["id"] >= 1000) if zs else (node_df["id"] < 1000)
students = node_df[students]
students

,id,sex,age,class,Atletika,Basketbal,Bricks 4 kidz,Dílnička pro holky,Florbal,Fotbal,...,Zájmové: Příprava k přijímacím zkouškám na SŠ - matematika,Zájmové: Počítačová grafika,asistent_trida1A,asistent_trida5A,pedagog3C,pedagog4C,pedagog5B,pedagog5C,x,y
55,1000,NaN,11,6B,0.0,1.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.800974,1.888506
56,1001,NaN,10,5A,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.029450,1.099600
57,1002,NaN,13,8A,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.247356,1.004051
58,1003,NaN,8,3B,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.080019,1.903633
59,1004,NaN,10,5A,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.839770,1.110674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
674,1626,NaN,7,2C,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.858112,2.941083
675,1627,NaN,7,2B,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.918972,2.148378
676,1628,NaN,7,2A,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.955486,1.015996
677,1629,NaN,7,2C,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.929262,3.114258
678,1630,NaN,7,2C,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.097124,3.045137

In [4]:
np.random.seed(seed)

for i in range(n_files):
    new_df = node_df.copy()
    students = (node_df["id"] >= 1000) if zs else (node_df["id"] < 1000)
    students = node_df[students]

    for student_class in sorted(students["class"].unique()):
        print()
        print(student_class)

        class_mask = students["class"] == student_class
        n_students = sum(class_mask)
        print(n_students)

        class_groups = np.where(np.arange(n_students) <= (n_students // 2), 0, 1)
        np.random.shuffle(class_groups)

        students.loc[class_mask, ["class_group"]] = class_groups

    new_df.to_csv(os.path.join(out_dir, f"nodes_student_groups_{i}.csv"))

1A
25

1B
26

1C
24

2A
20

2B
21

2C
25

3A
27

3B
30

3C
22

4A
20

4B
22

4C
25

5A
24

5B
23

5C
23

6A
28

6B
25

6C
22

7A
23

7B
21

7C
24

8A
26

8B
25

8C
21

9A
28

9B
24

1A
25

1B
26

1C
24

2A
20

2B
21

2C
25

3A
27

3B
30

3C
22

4A
20

4B
22

4C
25

5A
24

5B
23

5C
23

6A
28

6B
25

6C
22

7A
23

7B
21

7C
24

8A
26

8B
25

8C
21

9A
28

9B
24

1A
25

1B
26

1C
24

2A
20

2B
21

2C
25

3A
27

3B
30

3C
22

4A
20

4B
22

4C
25

5A
24

5B
23

5C
23

6A
28

6B
25

6C
22

7A
23

7B
21

7C
24

8A
26

8B
25

8C
21

9A
28

9B
24

1A
25

1B
26

1C
24

2A
20

2B
21

2C
25

3A
27

3B
30

3C
22

4A
20

4B
22

4C
25

5A
24

5B
23

5C
23

6A
28

6B
25

6C
22

7A
23

7B
21

7C
24

8A
26

8B
25

8C
21

9A
28

9B
24

1A
25

1B
26

1C
24

2A
20

2B
21

2C
25

3A
27

3B
30

3C
22

4A
20

4B
22

4C
25

5A
24

5B
23

5C
23

6A
28

6B
25

6C
22

7A
23

7B
21

7C
24

8A
26

8B
25

8C
21

9A
28

9B
24

/media/win_hdd/Gabi/Code/mff/ML/deep_learning_mff/.env38/lib/python3.8/site-packages/pandas/core/indexing.py:659: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[k] = np.nan
/media/win_hdd/Gabi/Code/mff/ML/deep_learning_mff/.env38/lib/python3.8/site-packages/pandas/core/indexing.py:1745: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
/media/win_hdd/Gabi/Code/mff/ML/deep_learning_mff/.env38/lib/python3.8/site-packages/pandas/core/indexing.py:659: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[k] = np.nan
/media/win_hdd/Gabi/Code/mff/ML/deep_learning_mff/.env38/lib/python3.8/site-packages/pandas/core/indexing.py:1745: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
/media/win_hdd/Gabi/Code/mff/ML/deep_learning_mff/.env38/lib/python3.8/site-packages/pandas/core/indexing.py:659: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[k] = np.nan
/media/win_hdd/Gabi/Code/mff/ML/deep_learning_mff/.env38/lib/python3.8/site-packages/pandas/core/indexing.py:1745: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
/media/win_hdd/Gabi/Code/mff/ML/deep_learning_mff/.env38/lib/python3.8/site-packages/pandas/core/indexing.py:659: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[k] = np.nan
/media/win_hdd/Gabi/Code/mff/ML/deep_learning_mff/.env38/lib/python3.8/site-packages/pandas/core/indexing.py:1745: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
/media/win_hdd/Gabi/Code/mff/ML/deep_learning_mff/.env38/lib/python3.8/site-packages/pandas/core/indexing.py:659: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[k] = np.nan
/media/win_hdd/Gabi/Code/mff/ML/deep_learning_mff/.env38/lib/python3.8/site-packages/pandas/core/indexing.py:1745: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)